name: PHP Composer

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]

jobs:
  analyse:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-php@master
        with:
          php-version: "7.3"

      - name: Update composer.lock
        run: composer update

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run analysis scripts
        run: composer run-script analyse
